### ISSUE TITLE
ERROR:  Could not find a valid gem

### ISSUE THREAD

**Issue by thomthom** [anolson/git_diff#8]
Tried to install the gem: `gem install git_diff`

But I get an error:
`ERROR:  Could not find a valid gem 'git_diff' (>= 0) in any repository`

Is it no longer available?

**Comment by anolson** [comment]
I don't believe I ever pushed a gem to RubyGems.  I can certainly do that, but in the meantime if you're using bundler add this to your `Gemfile`:

```
gem 'git_diff', git: 'https://github.com/anolson/git_diff.git'
```

**Comment by thomthom** [comment]
Ah, gotha. I just assumed it was on RubyGems due to the `gem install git_diff` line in the README. I am not using Bundler - I was just making a simple script for some automation.

**Comment by anolson** [comment]
Should be on RubyGems now. 🎉 

https://rubygems.org/gems/git_diff
